name: Create Security Fix Pull Request

on:
  push:
    branches:
      - master
  schedule:
    - cron: '00 03 * * *'

jobs:
  run-hothouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Setiing
        run: |
          npm install -g npm
          npm -v
          git config --global user.name hothouse
          git config --global user.email hothouse@example.com
          npm i -g hothouse
      - name: run
        run: |
          git config user.name
          git config user.email