name: Create Security Fix Pull Request

on:
  push:
    branches:
      - master
  schedule:
    - cron: '00 03 * * *'

jobs:
  run-hothouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Setiing
        run: |
          npm install -g npm
          npm -v
          npm i -g hothouse
      - name: run
        run: |
          git config --local user.name "hothouse"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          hothouse -t ${{ secrets.HOTHOUSE_TOKEN }}